name: Test For Pull Request

## Only run on PRs that are not for master.
on: 
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v1
      ## This installs the correct node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      ## This runs multiple commands to run.
      - name: npm ci, build, and test
        run: |
          npm ci
          npm run build
          npm test
    env:
      CI: true